version: '3'

services:
  phoenix1:
    build: .
    ports:
      - "4060:4060"
    environment:
      - PORT=4060
      - MY_APP_NODE=my_app
      - ERLANG_COOKIE=share_cookie
    networks:
      - phoenix_network

  phoenix2:
    build: .
    ports:
      - "4070:4070"
    environment:
      - PORT=4070
      - MY_APP_NODE=my_app2
      - ERLANG_COOKIE=share_cookie
    networks:
      - phoenix_network

  nginx:
    image: nginx
    ports:
      - "4080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - phoenix1
      - phoenix2
    networks:
      - phoenix_network

networks:
  phoenix_network:
    driver: bridge
